title: Anurag Benjwal
logo: /assets/img/logo.png
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/anurag-benjwal-73496556/">LinkedIn</a> |
  <a href="https://github.com/anuragbenjwal107">GitHub</a>
  
  <br>   
  I am working as Java developer, but now I want to make my carrier in data
  science field.
  <br>
  </p>
theme: jekyll-theme-minimal
